name: fastyle_dart_example
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  tbloc_dart: ^0.18.1
  
  fastyle_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
