name: fastyle_dart_example
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  tbloc_dart: ^0.19.0

  fastyle_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
