name: fastyle_dart_example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0

  t_helpers: ">=0.0.21 <2.0.0"
  tbloc: ">=0.21.0 <1.0.0"
  tmodel: ">=0.5.3 <1.0.0"

  fastyle_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
