name: fastyle_dart_example
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.26.0
  tbloc_dart: ^0.15.0-beta.0
  fastyle_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
