name: fastyle_dart_example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  tbloc_dart: ">=0.19.2 <1.0.0"
  google_fonts: ^3.0.1
  tutils_dart: ^1.0.0
  font_awesome_flutter: ^10.3.0
  go_router: ^6.0.9

  fastyle_dart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
