name: fastyle_dart
description: A new Flutter package project.
version: 0.22.1
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.6.1
  google_fonts: ^2.1.0
  intl: ^0.17.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.0.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.1
  another_flushbar: ^1.10.23
  tbloc_dart: ^0.16.1
  tmodel_dart: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.16.8
  dart_code_metrics: ^4.0.1
