name: fastyle_dart
description: Set of graphical Widgets.
version: 1.3.0
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.10.0
  google_fonts: ^4.0.4
  intl: ^0.18.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.2.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.7
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  decimal: ^2.3.2
  font_awesome_flutter: ^10.4.0
  go_router: ^7.1.1

  #internal

  t_helpers: ">=0.0.9+1 <2.0.0"
  tbloc: ">=0.21.0 <1.0.0"
  tmodel: ">=0.5.3 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_code_metrics: ^5.7.5
