name: fastyle_dart
description: Set of graphical Widgets.
version: 0.29.4
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.8.2
  google_fonts: ^3.0.1
  intl: ^0.17.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.1.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.3
  another_flushbar: ^1.10.29
  tbloc_dart: ^0.19.0
  tmodel_dart: ^0.4.0
  shimmer: ^2.0.0
  decimal: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.21.1
  dart_code_metrics: ^4.17.1
