name: fastyle_dart
description: A new Flutter package project.
version: 0.8.0
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  intl: ^0.16.1
  diacritic: ^0.1.1
  tbloc_dart: ^0.5.1
  flutter_spinkit: ^4.1.2+1
  fuzzy: ^0.2.3
  recase: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
