name: fastyle_dart
description: Set of graphical Widgets.
version: 0.33.0
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.9.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.1.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.5
  another_flushbar: ^1.12.29
  tbloc_dart: ^0.19.2
  tmodel_dart: ^0.5.0
  shimmer: ^2.0.0
  decimal: ^2.3.0
  tutils_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  test: ^1.21.4
  dart_code_metrics: ^4.19.1
