name: fastyle_dart
description: Set of graphical Widgets.
version: 1.1.1
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.10.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.1.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.7
  another_flushbar: ^1.12.29
  shimmer: ^2.0.0
  decimal: ^2.3.2
  font_awesome_flutter: ^10.4.0
  go_router: ^6.5.6

  #internal

  t_helpers: ">=0.0.7 <2.0.0"
  tbloc: ">=0.20.3 <1.0.0"
  tmodel: ">=0.5.1 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.2
