name: fastyle_dart
description: A new Flutter package project.
version: 0.22.0
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  collection: ^1.15.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  diacritic: ^0.1.3
  flutter_spinkit: ^5.0.0
  fuzzy: ^0.4.0-nullsafety.0
  rxdart: ^0.27.0
  another_flushbar: ^1.10.22
  meta: ^1.3.0
  tbloc_dart: ^0.15.0
  tmodel_dart: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
  dart_code_metrics: ^3.2.2
