name: fastyle_dart
description: A new Flutter package project.
version: 0.11.9
homepage: https://github.com/tyrcord/fastyle_dart

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.4.2
  collection: ^1.14.13
  google_fonts: ^1.1.1
  intl: ^0.16.1
  diacritic: ^0.1.1
  tbloc_dart: ^0.12.0
  flutter_spinkit: ^4.1.2+1
  fuzzy: ^0.2.3
  rxdart: ^0.24.1
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
